### ISSUE TITLE
Store IMDb results into MongoDB Atlas

### ISSUE THREAD

**Issue by spalabri** [jpcastil/TeamBananas#9]

**Comment by jpcastil** [comment]
Are we supposed to create our own local MongoDB server? 
Or can we opt to use a cloud hosted one?

Hosting our own seems like a nightmare @tdebbadcp

**Comment by jpcastil** [comment]
Time estimate: 4hrs

**Comment by jpcastil** [comment]
Could not complete this task due to lack of time while working on other stuff

**Comment by jpcastil** [comment]
Time estimate: 4hrs 
Time actual: 6hrs
